name: Deploy Model to AWS EC2
on:
  workflow_run:
    workflows: ["CI Pipeline"]  # Ensures this runs after train.yml completes
    types:
      - completed
  push:
    branches:
      - main
    tags:
      - 'latest' 
  workflow_dispatch:     
jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Check Self-Hosted Runner Status
        run: sudo systemctl status actions-runner || true
      - name: Pull Docker Image
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker pull $DOCKER_USER/vehicleinsurance-fastapi:latest
    
      - name: Delete Old Docker Container
        run: sudo docker rm -f vehicleinsurance-fastapi-container || true
    
      - name: Run Docker Container
        env: 
          DOCKER_USER: ${{ secrets.DOCKER_USER_NAME }}
        run: sudo docker run -it -d -p 8001:8001 --name vehicleinsurance-fastapi-container $DOCKER_USER/vehicleinsurance-fastapi:latest

